In [1]:
import numpy as np 
import pandas as pd

In [3]:
data = pd.read_csv(r"C:\Desktop\Anamika\ML0to1\Datasets\play_tennis.csv")

In [4]:
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [5]:
# Training -> Lookup 
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [6]:
py = 9/14
pn = 5/14

In [8]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [10]:
# outlook col...

pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [12]:
pon = 0
prn = 2/5 
psn = 3/5 
poy = 4/9
pry = 3/9
psy = 2/9

In [ ]:
# temperature col....
pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [15]:
pcoolno = 1/5
photno = 2/5 
pmildno= 2/5 
pcooly = 3/9
photy = 2/9 
pmildy = 4 / 9

In [17]:
# Humidity 

pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [19]:
phighn = 4 / 5 
pnorn = 1/ 5
phighy = 3/ 9 
pnory = 6 / 9

In [21]:
pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [22]:
pstrongn = 3/5
pweakn = 2/5 
pstrongy = 3/9 
pweaky = 6/9